Manthan patel hw1
iambillmccann/cs490-hw1 pull request #69
Opened 2023-01-22 02:40 UTC by manthan2905

2023-01-23 21:58 UTC, iambillmccann requested changes
You did not follow the assignment instructions. This is causing you to add a large number of files that do not belong in this code ... /EditPostPage, /NewPostPage, scaffold.css, etc. You need to revert your commits back to a point where there is only changes to Routes.js and /ManthanpatelPage.

2023-01-23 22:16 UTC, iambillmccann requested changes
I am curious how you managed to get those extraneous files into your code. You still need to back out the changes made to App.js.

2023-01-23 22:16 UTC, iambillmccann commented on web/src/App.js
> +import './scaffold.css'
You should not make any changes to App.js for this assignment.

2023-01-23 22:23 UTC, manthan2905 commented
I have by mistake used the terminal command under read me in the main branch and it added all the posts and added those extra files post. Thank you for your output I didn't know it kept all the changes. It did work under redwood when I checked so I thought it was done. My fault

2023-01-24 03:42 UTC, iambillmccann approved these changes

2023-01-24 03:42 UTC, merged